[build]
  base = "wayland-calendar-importer"
  command = "bun run build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"

[dev]
  framework = "nextjs"

# Netlify Next.js plugin configuration for App Router support
[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Robots-Tag = "noindex"
    Cache-Control = "no-store, no-cache, must-revalidate"
