name: Deploy to Vercel

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Test build (static mode)
      run: |
        export DISABLE_DATABASE=true
        export NODE_ENV=production
        bun run build
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
